---
title: "FRR"
author: "Kaitlyn Spangler"
date: "9/26/2019"
output: html_document
---
```{r message=F, warning=F}
library(sp)
library(tidyverse)

cty <- readRDS("./data/county.RDS")
frr <- read.csv("./data/FRR_data.csv") 
frr <- frr[,1:2]
colnames(frr)<- c("GEOID", "FRR")
frr$GEOID <- str_pad(frr$GEOID, width = 5, side = "left", pad= "0") 

#Identify any counties that may be missing in the FRR data? 
setdiff(unique(cty$GEOID), unique(frr$GEOID))

# Two were not included, so I added them in the FRR .csv file manually after checking where they belong (both belong in class 3)
# 46102 = Oglala Lakota Cty, SD 
# 08014 = Broomfield City and County, CO 

#Make spatial:
frr_shp <- merge(cty, frr, by = "GEOID")
spplot(frr_shp, "FRR")

getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

#Aggregate counties to the regional boundaries:
library(maptools)
frr_agg <- unionSpatialPolygons(SpP = frr_shp, IDs = frr_shp$FRR)
frr_final <- aggregate(frr_shp["FRR"], frr_agg, FUN = getmode)

saveRDS(frr_final, "frr.RDS")

#Color palettes 
library(RColorBrewer)
palette <- brewer.pal(n = 9, name = "Set3")
getPalette = colorRampPalette(brewer.pal(8, "Pastel2"))
palette2 <- getPalette(9)
library(colorspace)
palette3 <- qualitative_hcl(9, "Dynamic")
palette4 <- c("#CC6633", "#FFC300", "#99CCFF", "#4A7DA5", "#CCCCCC", "#646667", "#99CC99", "#336633", "#CCCC99")

#Plot
library(lattice)
trellis.par.set(axis.line=list(col=NA))
frr_plot <- spplot(frr_final, "FRR", col.regions = palette4, cuts = 8, col = "white", colorkey = list(labels = list( labels = c("Heartland","Northern Crescent","Northern Great Plains","Prairie Gateway","Eastern Uplands","Southern Seaboard","Fruitful Rim","Basin and Range", "Mississippi Portal"),        
                width = 0.4, cex = 0.75)))

frr_plot
```

# Make jpeg image 
```{r}
jpeg("FRR.jpg",
  width     = 7,
  height    = 5,
  units     = "in",
  res       = 300,
  pointsize = 4
  )
frr_plot
dev.off
```

#Tmap 
```{r}
library(tmap)

# wrap text for displaying on map
wrap.it <- function(x, len)
{ 
  sapply(x, function(y) paste(strwrap(y, len), 
                              collapse = "\n"), 
         USE.NAMES = FALSE)
}

# Call this function with a list or vector
wrap.labels <- function(x, len)
{
  if (is.list(x))
  {
    lapply(x, wrap.it, len)
  } else {
    wrap.it(x, len)
  }
}

#This applies the wrap.labels function to the names of the LRRs I'm ~*trying*~ to label. 

#This is the code for the map itself. All the specifications in "tm_text()" under "xmod=" and "ymod=" affect the spacing and positioning of the labels. 
#To adjust, I look at the order of LRRs in `n`. This order correlates to the number in the list of xmod and ymod numbers. It takes a lot of playing around to get them right--obviously, they STILL aren't right! I'll do the same to position the number of counties/LRR on the map! 
#xmod = L (-) to R (+)
#ymod = Up (+) to Down (-)

frr_final2 <- frr_final %>% 
	mutate(FRR_wrap = wrap.labels(FRR,9))

#Map

tm_shape(frr_final2)+
  tm_fill(col = "FRR") +
  tm_text("FRR_wrap", size=0.58, remove.overlap = F, along.lines = T, xmod=c(4.5,-0.1,0,0.3,1.1,0,-0.9,-0.3,-0.5), ymod=c(1,-0.5,-0.3,0,0,0,-0.1,0,-0.2)) +
  tm_text("FRR", size=0.4, col="black") +
  tm_legend(show=FALSE) +
  #tm_compass(text.size = 0.7,  color.dark = "gray30", text.color = "gray60", position = c("right", "bottom")) +
  #tm_scale_bar(color.dark = "gray30", position = c("right", "bottom"), text.size = 0.3) +
  tm_layout(frame = FALSE)
```

